### ISSUE TITLE
How do I visualize retrieved item?

### ISSUE THREAD

**Issue by tengyu-liu** [mikacuy/deformation_aware_embedding#2]
Thank you for sharing the code of your paper. Can you share how to visualize the retrieved and deformed example, as shown in figure 1?

**Comment by mikacuy** [comment]
Hi,

Thank you for your interest in our work. We used blender to render the meshes for the visualization in the paper.

The deformed meshes are created when you run the evaluation script (evaluate_fitting_deform_fast.py), a single pair can be evaluated by running (deform_retrieval_single_pair.py). Once you have the obj files, then you can render with your renderer of choice.

I uploaded the .blend blender file I used for the paper in the repo.

Best,
Mika

**Comment by tengyu-liu** [comment]
Thank you for your prompt reply. I'm having trouble compiling the meshdeform package. Can you provide a guide on how to compile the cpp tools?

**Comment by tengyu-liu** [comment]
Nevermind I've figured it out :)
