### ISSUE TITLE
Eigen failed in deform and getcost when running on custom objects

### ISSUE THREAD

**Issue by tengyu-liu** [mikacuy/deformation_aware_embedding#3]
Hi, 

I am trying to run `evaluate_fitting_deform_fast.py` on my custom objects, and am receiving the following errors: 

    $ python my_evaluate_fitting_deform_fast.py
    Deform True
    No handlers could be found for logger "trimesh"
    Number of commands in parallel: 6
    Source:         Num vertices: 6469      Num faces: 12934
    Reference:      Num vertices: 256       Num faces: 494
    
    Source:         Num vertices: 5000      Num faces: 10000
    Reference:      Num vertices: 516       Num faces: 936
    
    Source:         Num vertices: 7413      Num faces: 14822
    Reference:      Num vertices: 516       Num faces: 936
    
    Source:         Num vertices: 5000      Num faces: 10000
    Reference:      Num vertices: 256       Num faces: 494
    
    Source:         Num vertices: 8243      Num faces: 16482
    Reference:      Num vertices: 516       Num faces: 936
    
    Source:         Num vertices: 7413      Num faces: 14822
    Reference:      Num vertices: 256       Num faces: 494
    
    deform: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1;int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    deform: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1;int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    Aborted (core dumped)
    Source:         Num vertices: 0 Num faces: 0
    Reference:      Num vertices: 256       Num faces: 494
    
    deform: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1;int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    deform: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1;int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    deform: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1;int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    Aborted (core dumped)
    Source:         Num vertices: 0 Num faces: 0
    Reference:      Num vertices: 256       Num faces: 494
    
    deform: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1;int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    Aborted (core dumped)
    Aborted (core dumped)
    Source:         Num vertices: 0 Num faces: 0
    Reference:      Num vertices: 516       Num faces: 936
    
    Source:         Num vertices: 0 Num faces: 0
    Reference:      Num vertices: 516       Num faces: 936
    
    Aborted (core dumped)
    Source:         Num vertices: 0 Num faces: 0
    Reference:      Num vertices: 516       Num faces: 936
    
    Aborted (core dumped)
    Source:         Num vertices: 0 Num faces: 0
    Reference:      Num vertices: 256       Num faces: 494
    
    getcost: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    getcost: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    getcost: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    Aborted (core dumped)
    Aborted (core dumped)
    getcost: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    [18:53:50.848846] command 0 of 6
    getcost: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    Aborted (core dumped)
    getcost: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1; int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
    Aborted (core dumped)
    Aborted (core dumped)
    Aborted (core dumped)
    Time elapsed: 2.59997701645 sec.

I'm wondering if you know what this error is, and how I can approach it. Could it be related to the fact that my objects are much smaller in terms of # of faces and # of vertices?

**Comment by mikacuy** [comment]
Hi, 

Are your objects normalized into a unit sphere and centered? It seems that the error is in the distance field conversion.

Best,
Mika

**Comment by tengyu-liu** [comment]
Thank you for looking into this. I re-ran the program on zero-centered and normalized obj files and the problem persists. 

```
Source:         Num vertices: 3506      Num faces: 2992
Reference:      Num vertices: 1560      Num faces: 1746

deform: /usr/local/include/eigen3/Eigen/src/Core/Block.h:122: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Index) [with XprType = const Eigen::Matrix<double, -1, -1>; int BlockRows = 1;int BlockCols = -1; bool InnerPanel = false; Eigen::Index = long int]: Assertion `(i>=0) && ( ((BlockRows==1) && (BlockCols==XprType::ColsAtCompileTime) && i<xpr.rows()) ||((BlockRows==XprType::RowsAtCompileTime) && (BlockCols==1) && i<xpr.cols()))' failed.
```

**Comment by mikacuy** [comment]
It seems that from the first comment, there are examples where there are 0 source vertices and 0 source faces. I think typically this error happens when the matrix is empty.

**Comment by tengyu-liu** [comment]
I'm currently running this on just a single pair of obj files, both of which have valid vertices and faces. I realized that this is a lot to ask, but would you mind if I send you the obj files so you can take a look at what might be the error?

**Comment by tengyu-liu** [comment]
Nevermind I removed all the textures in both files and it seems to be working now! Thank you so much for the help!
