### ISSUE TITLE
Dependencies (requirements.txt file)

### ISSUE THREAD

**Issue by Shreyas-Gururaj** [mikacuy/deformation_aware_embedding#5]
Dear Mikacuy,

I was going through your paper "Deformation-Aware 3D Model Embedding and Retrieval" and found it very interesting for one of my projects. It would be helpful if I can obtain the requirements.txt file capturing the versions of the modules imported for running the codebase for my own dataset.

Shreyas Gururaj. @mikacuy @mhsung @tolgabirdal

**Comment by mikacuy** [comment]
Hi Shreyas,

Thank you for your interest in our work. I just uploaded the requirements.txt file into the github repo.

Best,
Mika

**Comment by Shreyas-Gururaj** [comment]
Hi Mikacuy,

Thank you very much for you prompt response. I really appreciate the kind gesture.

Warm Regards,
Shreyas Gururaj.
